import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TaskList from '@/components/taskList/taskList'
import { Task } from '@prisma/client'
import Link from 'next/link'
import { getTasks } from '@/lib/task'
import UsernameTag from '@/components/usernameTag/usernameTag'
import { RootState } from '@/store'
import { useSelector } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })



type Props = {
  tasks: Task[]
}

export default function Home(props : Props) {
  const { tasks } = props;
  const username = useSelector((state: RootState) => state.username.value)

  return (
    <>
      <Head>
        <title>Manage my task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Manage my task</h1>
        <UsernameTag username={username}/>
        <Link href={"/tasks"}>Manage Tasks</Link>
        <Link href={"/users"}>Users portal</Link>
       <TaskList tasks={tasks}/>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const tasks = await getTasks();

  return {
      props: {
          tasks
      }
  }
}

